package com.til.recasting.constant;

import mods.flammpfeil.slashblade.registry.slashblade.SlashBladeDefinition;
import net.minecraft.resources.ResourceKey;

import java.util.List;

/**
 * 创造栏命名刀展示顺序，与 {@code SlashBladeDefinitions.registerAll} 中实际 register 调用一致。
 */
public final class RecastingSlashBladeCreativeOrder {

    public static final List<ResourceKey<SlashBladeDefinition>> CREATIVE_TAB_ORDER = List.of(
            RecastingSlashBladeKeys.BROADSWORD_WOOD,
            RecastingSlashBladeKeys.GREEN_BLADE_WOOD,
            RecastingSlashBladeKeys.DHARMA_STICK,
            RecastingSlashBladeKeys.DHARMA_STICK_LAMBDA,
            RecastingSlashBladeKeys.HOE,
            RecastingSlashBladeKeys.PHYSICS_SWORD,
            RecastingSlashBladeKeys.ART_KNIFE,
            RecastingSlashBladeKeys.JIE_YUAN_DOG,
            RecastingSlashBladeKeys.BROADSWORD_IRON,
            RecastingSlashBladeKeys.GREEN_BLADE_IRON,
            RecastingSlashBladeKeys.BROKEN_WHITE,
            RecastingSlashBladeKeys.BLACK,
            RecastingSlashBladeKeys.BA_GUA,
            RecastingSlashBladeKeys.BLUE_CLOUD,
            RecastingSlashBladeKeys.BLUE_CLOUD_LAMBDA,
            RecastingSlashBladeKeys.DRAGON_SCALE,
            RecastingSlashBladeKeys.DRAGON_SCALE_LAMBDA,
            RecastingSlashBladeKeys.UMBRELLA,
            RecastingSlashBladeKeys.UMBRELLA_LAMBDA,
            RecastingSlashBladeKeys.BA_GUA_BIG,
            RecastingSlashBladeKeys.BA_GUA_BIG_LAMBDA,
            RecastingSlashBladeKeys.OBLITERATE,
            RecastingSlashBladeKeys.OBLITERATE_LAMBDA,
            RecastingSlashBladeKeys.SHINE_GOLD,
            RecastingSlashBladeKeys.SHINE_GOLD_LAMBDA,
            RecastingSlashBladeKeys.SHINE_TEA,
            RecastingSlashBladeKeys.SHINE_TEA_LAMBDA,
            RecastingSlashBladeKeys.SILVER_WING,
            RecastingSlashBladeKeys.SILVER_WING_LAMBDA,
            RecastingSlashBladeKeys.LONG_SKY_SUNSET,
            RecastingSlashBladeKeys.LONG_SKY_SUNSET_LAMBDA,
            RecastingSlashBladeKeys.XUAN_MING,
            RecastingSlashBladeKeys.XUAN_MING_LAMBDA,
            RecastingSlashBladeKeys.AZURE_VISTA,
            RecastingSlashBladeKeys.AZURE_VISTA_LAMBDA,
            RecastingSlashBladeKeys.RADIANT_STAR,
            RecastingSlashBladeKeys.COOL_MINT,
            RecastingSlashBladeKeys.COOL_MINT_LAMBDA,
            RecastingSlashBladeKeys.COLOR_WING,
            RecastingSlashBladeKeys.COLOR_WING_LAMBDA,
            RecastingSlashBladeKeys.DRAGON,
            RecastingSlashBladeKeys.DRAGON_LAMBDA,
            RecastingSlashBladeKeys.SOULBLADE,
            RecastingSlashBladeKeys.SOULBLADE_LAMBDA,
            RecastingSlashBladeKeys.SUPREME_POLE,
            RecastingSlashBladeKeys.SUPREME_POLE_LAMBDA,
            RecastingSlashBladeKeys.WIND_CLOUD,
            RecastingSlashBladeKeys.WIND_CLOUD_LAMBDA,
            RecastingSlashBladeKeys.BRILLIANT_GOLD,
            RecastingSlashBladeKeys.BRILLIANT_GOLD_LAMBDA,
            RecastingSlashBladeKeys.BRILLIANT_TEA,
            RecastingSlashBladeKeys.BRILLIANT_TEA_LAMBDA,
            RecastingSlashBladeKeys.STARTLED_SWAN,
            RecastingSlashBladeKeys.STARTLED_SWAN_LAMBDA,
            RecastingSlashBladeKeys.BRIARLAND,
            RecastingSlashBladeKeys.BRIARLAND_LAMBDA,
            RecastingSlashBladeKeys.ONIKIRI,
            RecastingSlashBladeKeys.ONIKIRI_LAMBDA,
            RecastingSlashBladeKeys.STAR_THREAD,
            RecastingSlashBladeKeys.STAR_THREAD_LAMBDA,
            RecastingSlashBladeKeys.FINAL_GLOW,
            RecastingSlashBladeKeys.FINAL_GLOW_LAMBDA,
            RecastingSlashBladeKeys.VAULT_SCALE,
            RecastingSlashBladeKeys.VAULT_SCALE_LAMBDA,
            RecastingSlashBladeKeys.TU_WU,
            RecastingSlashBladeKeys.TU_WU_LAMBDA,
            RecastingSlashBladeKeys.XUAN_YUAN_LIBERATED,
            RecastingSlashBladeKeys.XUAN_YUAN_LIBERATED_LAMBDA,
            RecastingSlashBladeKeys.FLUORESCENCE_1,
            RecastingSlashBladeKeys.FLUORESCENCE_2,
            RecastingSlashBladeKeys.FLUORESCENCE_3,
            RecastingSlashBladeKeys.FLUORESCENCE_4,
            RecastingSlashBladeKeys.FLUORESCENCE_5,
            RecastingSlashBladeKeys.FLUORESCENCE_6,
            RecastingSlashBladeKeys.FLUORESCENCE_7,
            RecastingSlashBladeKeys.FLUORESCENCE_8,
            RecastingSlashBladeKeys.LASER_1,
            RecastingSlashBladeKeys.LASER_2,
            RecastingSlashBladeKeys.LASER_3,
            RecastingSlashBladeKeys.LASER_3_LAMBDA,
            RecastingSlashBladeKeys.MAGNETIC_STORM,
            RecastingSlashBladeKeys.MAGNETIC_STORM_LAMBDA,
            RecastingSlashBladeKeys.MAGNETIC_STORM_LIMITS,
            RecastingSlashBladeKeys.MAGNETIC_STORM_LIMITS_LAMBDA,
            RecastingSlashBladeKeys.STAR_1,
            RecastingSlashBladeKeys.STAR_2,
            RecastingSlashBladeKeys.STAR_3,
            RecastingSlashBladeKeys.STAR_4,
            RecastingSlashBladeKeys.STAR_4_LAMBDA,
            RecastingSlashBladeKeys.VOID_1,
            RecastingSlashBladeKeys.VOID_2,
            RecastingSlashBladeKeys.VOID_3
    );

    private RecastingSlashBladeCreativeOrder() {
    }
}
